### ISSUE TITLE
Initial Setup and Project Scaffolding

### ISSUE THREAD

**Issue by Kroszborg** [The-Red-Wood-Lab/Time-capsule-website#1]
Issue Title: Set up project structure and environment

Description: Initialize the project with Next.js (or any other framework), TailwindCSS, and basic dependencies (e.g., file upload libraries, date libraries).

Tasks:

-     Create the file structure (pages, components, assets, etc.).
-     Add TailwindCSS and configure it.
-     Set up version control (.gitignore, README, etc.).

Please comment on this issue if you'd like to work on any of these tasks or if you have any questions or suggestions.

#hacktoberfest

**Comment by Kroszborg** [comment]
Assigned to @Blackie360  kindly proceed as per format. I hope it is clear how to submit PR. please give a thumbs up if you got it almost all the things mentioned in issue's description.

**Comment by eeshan15** [comment]
Great work @Kroszborg Please keep in mind that there is a cooldown period of 1 PR for example if Felix submitted his PR and got merge so he cannot submit the next PR of some new issue other guy or probably you will proceed submitting. After that @Blackie360 will get chance once again to solve the issue. Incase you @Kroszborg is submitting the PR than there will be a mutual discussion amongst the fellow participants and outcomes are implemented in the PR accordingly. Hope that suits and clear. Please if you know the Backend part of the website kindly implement that as well. Thank you and keep it up guys

**Comment by Kroszborg** [comment]
Okay, my specialty is Front-end but I will look into implementing the backend as well

**Comment by Blackie360** [comment]
will we also use shadcn ?

**Comment by Kroszborg** [comment]
> will we also use shadcn ?

I'm currently working on the frontend, but yes you can use any open source library or components you need

**Comment by Blackie360** [comment]
> > will we also use shadcn ?
> 
> I'm currently working on the frontend, but yes you can use any open source library or components you need

I am initializing the project or you have already done that

**Comment by Kroszborg** [comment]
i have already done that, im pushing the changes

**Comment by Kroszborg** [comment]
> okey Push the changes then I make a copy from you

Finished pushing the pull request rn

**Comment by Blackie360** [comment]
> > okey Push the changes then I make a copy from you
> 
> Finished pushing the pull request rn

why create react why not vite   or next js 

CRA has a long build time and produces large bundle sizes because it doesn't support tree-shaking as effectively as modern tools.
In production, CRA doesn't provide advanced optimizations like server-side rendering (SSR) or code-splitting by default, leading to slower initial load times.

**Comment by Kroszborg** [comment]
> > > okey Push the changes then I make a copy from you
> > 
> > 
> > Finished pushing the pull request rn
> 
> why create react why not vite or next js
> 
> CRA has a long build time and produces large bundle sizes because it doesn't support tree-shaking as effectively as modern tools. In production, CRA doesn't provide advanced optimizations like server-side rendering (SSR) or code-splitting by default, leading to slower initial load times.

implicity: CRA is straightforward to set up, making it great for beginners.
Built-in Features: Comes with a lot of built-in features like ESLint, Jest for testing, and a development server with hot module replacement.
Community Support: Being one of the most popular ways to create React applications, it has extensive community support and documentation.
This is just for project setup if everyone votes for it, we can switch to vite, next or remix

**Comment by eeshan15** [comment]
Great work Guys one succesful merge has been done @Kroszborg @Blackie360. Now Felix gets a PR cool down and will deal with next issue meanwile @Kroszborg will deal this PR. Please have a mutual Discussion for that like you did this. Keep the good work guys

**Comment by eeshan15** [comment]
@Kroszborg @Blackie360  You can discuss these type of stuff in discussion group on whatsapp. Please remember after issue has been closed than you should not discuss other stuff. Kindly Follow the instructions thank you

**Comment by Blackie360** [comment]
> @Blackie360 you know how to do backend? i can make the issue for you

I know some basic backend
