### ISSUE TITLE
Implement user authentication

### ISSUE THREAD

**Issue by Kroszborg** [The-Red-Wood-Lab/Time-capsule-website#3]
Description: Enable users to register and log in. This can be done via email/password or OAuth.
Tasks:
        - Set up user registration.
        - Implement login and session management.
        - Add password encryption for security.
        - Create authentication middleware to protect certain routes.

Please comment on this issue if you'd like to work on any of these tasks or if you have any questions or suggestions.

#hacktoberfest

**Comment by Kroszborg** [comment]
assigned this issue to @Blackie360, give updates so i can close this issue after you complete the work

**Comment by Blackie360** [comment]
Opened a PR 
changed  the codebase to vite also implemented auth  with clerk but will also need to fine tune  it  for the user journey

**Comment by Kroszborg** [comment]
Closed the issue as its completed

**Comment by Kroszborg** [comment]
@Blackie360 repush your pr

**Comment by Blackie360** [comment]
am pushing it right now
