### ISSUE TITLE
Create UI for time capsule creation

### ISSUE THREAD

**Issue by Kroszborg** [The-Red-Wood-Lab/Time-capsule-website#5]
- Description: Build the form where users can upload files, messages, and images to create a time capsule.
- Tasks:
    - Create fields for message input, file upload, and image upload.
    - Implement a date picker for setting the reveal date.
    - Add validation (e.g., required fields, file size limits).

**Comment by Blackie360** [comment]
Sorry for the hold up I found I had done a mistake on the auth I have refined the Auth flow ,LOl am used to Next js I almost forgot the basic things in react js such as routes and protecting them

**Comment by Kroszborg** [comment]
okay no problem

**Comment by Kroszborg** [comment]
you are still working on this issue right?

**Comment by MundiaNderi** [comment]
If no one is working on this issue, I'm interested in it.

**Comment by Blackie360** [comment]
> you are still working on this issue right?

opened a pr on it

**Comment by Blackie360** [comment]
> If no one is working on this issue, I'm interested in it.

you can pick the reveal time capsule issue if you dont mind

**Comment by Kroszborg** [comment]
> If no one is working on this issue, I'm interested in it.

@Blackie360 is working on this one, you can ask to be assigned to a new one @MundiaNderi
